### PR TITLE
3.0.0-preview6 changes

### PR DESCRIPTION
**Pull request by MarkStega**
Modest changes required for preview6 compatibility; Used Newtonsoft.Json rather than System.Text.Json after running into serialization/deserialization issues in another project. This can be revisited after System.Text.Json stabilizes.

### CODE REVIEW

**Comment by StevenTCramer** [comment]
Thank's Mark for doing this PR

**Comment by MarkStega** [comment]
I suspect that the CI build failure is because the CLI is preview4

**Comment by galvesribeiro** [comment]
Hello @MarkStega , can you update the PR so the build pass? Thank you!

**Comment by MarkStega** [comment]
@galvesribeiro The CI build failure was likely caused because the CLI in the build was preview4. The build logs are no longer available. I believe if you update the build environment to preview6 & force a rebuild all will be well.

**Comment by chucker** [comment]
> The CI build failure was likely caused because the CLI in the build was preview4.

I think @galvesribeiro is asking if you could edit the `.vsts-ci.yml` file accordingly in your PR.

**Comment by MarkStega** [comment]
@chucker I didn't know that there were yml files in the solution or what they were for. I updated the SDK version as well as adding them as solution items so that they were visible when using Visual Studio.

**Comment by MarkStega** [comment]
@galvesribeiro With the assistance of @chucker I discovered that yml files were part of the project and what their use was. They are now updated & the CI build passes.

**Comment by galvesribeiro** [comment]
Thank you both!

**Pull request merged**
