### PR TITLE
Updates to work with Blazor 3.0.0-preview4

### PR DESCRIPTION
**Pull request by DanielCarmingham**
Minimal changes to get it working with Blazor 3.0.0-preview4.

### CODE REVIEW

**Comment by galvesribeiro** [comment]
Thanks again @DanielCarmingham! Reviewing/merging soon!

**Comment by Hawxy** [comment]
Just a note with this and other projects you're updating, component libraries should probably be updated to the new Blazor Library template (where possible).

`Microsoft.NET.Sdk.Web` -> `Microsoft.NET.Sdk.Razor`

Remove `<OutputType>`
Add `<AddRazorSupportForMvc>true</AddRazorSupportForMvc>` (To be removed in next preview version)

Remove any `Microsoft.AspNetCore.Blazor.*` references and change it to a single `Microsoft.AspNetCore.Components.Browser`

**Comment by DanielCarmingham** [comment]
Added another commit with the changes recommended by @Hawxy to make it more similar to the blazorlib templates:

* `Microsoft.NET.Sdk.Web` -> `Microsoft.NET.Sdk.Razor`
* Remove `<OutputType>`
* Add `<AddRazorSupportForMvc>true</AddRazorSupportForMvc>`
* Replaced Remove `Microsoft.AspNetCore.Blazor.*` references with single `Microsoft.AspNetCore.Components.Browser reference`

Although these don't provide any direct benefit here, I added these to be consistent with the blazorlib template.  (I find it makes it easier to upgrade between Blazor releases when you can easily see the changes.)

* Added `<LangVersion>` `<RazorLangVersion>` `<RestoreAdditionalPackageSources>` as are in the blazorlib template.  

If you'd rather pull these out, just let me know, I could go either way on this...

Thanks,
Daniel

**Comment by galvesribeiro** [comment]
@DanielCarmingham thanks again for doing this.

Can you do me a favor and let me know on all the PRs you made when it is done for review? 

Thank you!

**Comment by DanielCarmingham** [comment]
@galvesribeiro Yeah, sorry about that.  My initial attempt was to do as little as possible to get them working on 3.0.0-preview4.  However, as @Hawxy pointed out, there are some things that, even though they work, aren't quite right.

This one is ready for review.  I'll comment on the other repos individually.  THANK YOU for your efforts on these projects and for taking the time to review my PR.  I sincerely appreciate it.

Thanks,
Daniel

**Comment by galvesribeiro** [comment]
Thank you @DanielCarmingham !!!

**Comment by IvanJosipovic** [comment]
@galvesribeiro We're still missing the nuget update.

**Comment by galvesribeiro** [comment]
The updates for all the packages will come tonight. I need to reset the NuGet key on all Azure Pipeline build servers so it can push the packages (they expired). Hang on!

**Pull request merged**
